// client-react/Produto/Produtos.js
import React, { useState, useEffect } from 'react';

const Produtos = () => {
    const [produtos, setProdutos] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    useEffect(() => {
        fetch('http://localhost:8000/produtos/listar.php')
            .then(response => {
                if (!response.ok) {
                    throw new Error('Erro ao buscar os dados');
                }
                return response.json();
            })
            .then(data => {
                setProdutos(data);
                setLoading(false);
            })
            .catch(error => {
                setError(error.message);
                setLoading(false);
            });
    }, []);

    if (loading) {
        return <div>Carregando...</div>;
    }

    if (error) {
        return <div>Erro: {error}</div>;
    }

    return (
        <div>
            <h1>Lista de Produtos</h1>
            <ul>
                {produtos.map(produto => (
                    <li key={produto.id}>{produto.nome} - {produto.preco}</li>
                ))}
            </ul>
        </div>
    );
};

export default Produtos;

// client/src/components/Produtos.vue
<template>
  <div>
    <h1>Cadastro Produtos</h1>

    <!-- Formulário de pedidos -->
    <form @submit.prevent="submitPedido">
      <label for="produto">Produto:</label>
      <input type="text" id="produto" v-model="produto">
      
      <label for="quantidade">Quantidade:</label>
      <input type="number" id="quantidade" v-model.number="quantidade">
      
      <label for="preco">Preço Unitário:</label>
      <input type="number" id="preco" v-model.number="preco">
      
      <button type="submit">Adicionar Pedido</button>
    </form>


  </div>
</template>

<script>

export default {
    data() {
      return {
        message: ''
      };
    },
    mounted() {
      fetch('http://localhost:8000/index.php')
        .then(response => response.json())
        .then(data => {
          this.message = data.message;
        })
        .catch(error => {
          console.error('Error fetching data:', error);
        });
    }
  };

</script>
